### ISSUE TITLE
部署时报错

### ISSUE THREAD

**Issue by MHXXX** [Mereithhh/van-blog#2]
错误内容
```
/app/server/provider/meta/meta.provider.js:133
        return (await this.getAll()).siteInfo;
                                     ^

TypeError: Cannot read properties of null (reading 'siteInfo')
    at MetaProvider.getSiteInfo (/app/server/provider/meta/meta.provider.js:133:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WalineProvider.init (/app/server/provider/waline/waline.provider.js:43:26)

```

**Comment by MHXXX** [comment]
部署方式: docker-compose

**Comment by liqingyou** [comment]
i have the same error

**Comment by Mereithhh** [comment]
不好意思😅，这是加 feature 的时没考虑到初始化情景导致的 bug ，已经修复了。麻烦重新删除一下镜像再重新部署一下应该就好了。

**Comment by Mereithhh** [comment]
不好意思😅，这是昨天加 feature 没考虑到初始化场景导致的 bug，已经修复了。删除镜像重新拉一下应该就好了。

另外因为阿里云镜像有时候会触发限流，所以默认改成 DockerHub 的了😅

```bash
docker rmi registry.cn-beijing.aliyuncs.com/mereith/van-blog:latest
# 这个改成默认的了
mereith/van-blog:latest
```

**Comment by MHXXX** [comment]
> 不好意思😅，这是昨天加 feature 没考虑到初始化场景导致的 bug，已经修复了。删除镜像重新拉一下应该就好了。
> 
> 另外因为阿里云镜像有时候会触发限流，如果慢的话可以考虑用 DockerHub 的😅
> 
> ```shell
> docker rmi registry.cn-beijing.aliyuncs.com/mereith/van-blog:latest
> # 这个改成默认的了
> mereith/van-blog:latest
> ```


刚试了一下, 又报这个错误
```
[Nest] 27  - 08/26/2022, 5:38:58 PM     LOG [ISRProvider] 首次启动触发全量渲染！
/app/server/provider/category/category.provider.js:52
            throw new common_1.NotFoundException();
                  ^

NotFoundException: Not Found
    at CategoryProvider.getAllCategories (/app/server/provider/category/category.provider.js:52:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ISRProvider.getCategoryUrls (/app/server/provider/isr/isr.provider.js:179:28)
    at async ISRProvider.activePath (/app/server/provider/isr/isr.provider.js:95:38)
    at async Promise.all (index 1) {
  response: { statusCode: 404, message: 'Not Found' },
  status: 404
}
```

**Comment by Mereithhh** [comment]
您再试一下，我又修了一下😂
